-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- Enable auto hard wrap at 80 characters for markdown files
-- vim.api.nvim_create_autocmd("FileType", {
-- 	pattern = { "markdown" },
-- 	callback = function()
-- 		vim.opt_local.textwidth = 80
-- 		vim.opt_local.formatoptions:append("t")
-- 	end,
-- })
