return {
	{
		"mason-org/mason.nvim",
		event = "VeryLazy",
		opts = {
			ensure_installed = {
				"clangd",
				"cmakelang",
				"cmakelint",
				"codelldb",
				"debugpy",
				"delve",
				"docker-compose-language-service",
				"dockerfile-language-server",
				"gofumpt",
				"goimports",
				"golangci-lint",
				"gopls",
				"hadolint",
				"js-debug-adapter",
				"json-lsp",
				"ltex-ls",
				"lua-language-server",
				"markdown-toc",
				"markdownlint-cli2",
				"marksman",
				"neocmakelsp",
				"nil",
				"prettier",
				"pyproject-fmt",
				"pyright",
				"ruff",
				"shfmt",
				"stylua",
				"tailwindcss-language-server",
				"taplo",
				"texlab",
				"tree-sitter-cli",
				"vtsls",
				"yaml-language-server",
			},
		},
	},
}
