{
  pkgs,
  lib,
  ...
}:
{
  options.new = lib.mkEnableOption "new";
  config = {
    home.packages = with pkgs; [
      act
      bat
      cargo
      cmatrix
      commitizen
      cookiecutter
      delta
      doppler
      dust
      eza
      fastfetch
      fd
      ffmpeg-full
      gh
      ghostscript
      go
      gum
      hyperfine
      imagemagick
      jq
      just
      kubernetes-helm
      lazydocker
      lazygit
      ltex-ls
      lua5_1
      lua51Packages.luarocks
      markdownlint-cli2
      markdownlint-cli2
      marksman
      mermaid-cli
      nixfmt-rfc-style
      nmap
      nodejs_24
      openconnect
      pandoc
      pnpm
      pre-commit
      prettier
      prettierd
      (lib.lowPrio python312)
      (lib.hiPrio python313)
      ripgrep
      ruff
      speedtest-cli
      scc
      statix
      stylua
      taplo
      tealdeer
      texliveFull
      tmux
      tree-sitter
      ttyper
      uv
      watch
      wget
      yazi
      yt-dlp
      zathura
      zsh-fzf-tab
    ];
  };
}
