{
  pkgs,
  lib,
  inputs,
  ...
}:
{
  config = {
    home.packages = with pkgs; [
      inputs.nix-auth.packages.${pkgs.stdenv.hostPlatform.system}.default
      act
      bat
      bibtex-tidy
      cmatrix
      commitizen
      cookiecutter
      crush
      delta
      devenv
      doppler
      dust
      eza
      fastfetch
      fd
      ffmpeg-full
      gh
      ghostscript
      glow
      go
      gum
      hyperfine
      imagemagick
      jq
      just
      kubernetes-helm
      lazydocker
      lazygit
      less
      ltex-ls
      lua51Packages.luarocks
      lua5_1
      markdownlint-cli2
      marksman
      mermaid-cli
      nixfmt
      nmap
      nodejs_24
      openconnect
      pandoc
      pnpm
      pre-commit
      prettier
      prettierd
      ripgrep
      ruff
      scc
      speedtest-cli
      statix
      stylua
      taplo
      tealdeer
      texliveFull
      tmux
      tree-sitter
      ttyper
      unzip
      uv
      watch
      wget
      yazi
      yt-dlp
      zathura
      zsh-fzf-tab
    ];

    home.activation.uvPython = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      UV_PATH="/usr/bin:/bin:/usr/sbin:/sbin:$HOME/.local/bin:$PATH"
      PATH="$UV_PATH" ${pkgs.uv}/bin/uv python install 3.12 3.13
      PATH="$UV_PATH" ${pkgs.uv}/bin/uv python pin --global 3.12
    '';
  };
}
