{
  pkgs,
  lib,
  inputs,
  ...
}:
{
  config = {
    home.packages = with pkgs; [
      inputs.nix-auth.packages.${pkgs.stdenv.hostPlatform.system}.default
      act
      bat
      cmatrix
      commitizen
      cookiecutter
      crush
      delta
      devenv
      doppler
      dust
      eza
      fastfetch
      fd
      ffmpeg-full
      gh
      ghostscript
      go
      gum
      hyperfine
      imagemagick
      jq
      just
      kubernetes-helm
      lazydocker
      lazygit
      ltex-ls
      lua51Packages.luarocks
      lua5_1
      markdownlint-cli2
      marksman
      mermaid-cli
      nixfmt
      nmap
      nodejs_24
      openconnect
      pandoc
      pnpm
      pre-commit
      prettier
      prettierd
      (lib.lowPrio python312)
      (lib.hiPrio python313)
      ripgrep
      ruff
      scc
      speedtest-cli
      statix
      stylua
      taplo
      tealdeer
      texliveFull
      tmux
      tree-sitter
      ttyper
      unzip
      uv
      watch
      wget
      yazi
      yt-dlp
      zathura
      zsh-fzf-tab
    ];
  };
}
