[language-server.pyright-langserver]
command = "pyright-langserver"
args = ["--stdio"]
config = {} # <- this is the important line

[[language]]
name = "python"
roots = ["pyproject.toml"]
language-servers = ["pyright-langserver"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG"]
roots = [".marksman.toml"]
language-servers = ["marksman"]
indent = { tab-width = 2, unit = "  " }
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true
